# -*- coding: utf-8 -*-
"""Proyecto Final - Programacion Orientada a Objetos - Diego Moreno Davila

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YuTs9JLUl9J_yyXzDwxDWBu-TCn4r0VI
"""

!pip install -q streamlit

!pip install streamlit yagmail

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import csv
# from datetime import datetime
# import yagmail
# import streamlit as st
# from random import choice
# 
# # Clase: GestorCumpleaños
# class GestorCumpleaños:
#     def __init__(self, archivo_datos="cumpleaños.csv"):
#         self.archivo_datos = archivo_datos
#         self.lista_cumpleaños = []
#         self.cargar_cumpleaños()
# 
#     def cargar_cumpleaños(self):
#         """Lee los datos de cumpleaños desde un archivo CSV."""
#         try:
#             with open(self.archivo_datos, mode='r', encoding='utf-8') as archivo:
#                 lector = csv.DictReader(archivo)
#                 self.lista_cumpleaños = list(lector)
#         except FileNotFoundError:
#             self.lista_cumpleaños = []
# 
#     def guardar_cumpleaños(self):
#         """Escribe los datos de cumpleaños al archivo CSV."""
#         with open(self.archivo_datos, mode='w', newline='', encoding='utf-8') as archivo:
#             columnas = ['nombre', 'correo', 'fecha_nacimiento']
#             escritor = csv.DictWriter(archivo, fieldnames=columnas)
#             escritor.writeheader()
#             escritor.writerows(self.lista_cumpleaños)
# 
#     def agregar_cumpleaños(self, nombre, correo, fecha_nacimiento):
#         """Añade un nuevo cumpleaños a la lista."""
#         self.lista_cumpleaños.append({
#             "nombre": nombre.strip(),
#             "correo": correo.strip(),
#             "fecha_nacimiento": fecha_nacimiento
#         })
#         self.guardar_cumpleaños()
# 
#     def eliminar_cumpleaños(self, nombre):
#         """Elimina un cumpleaños basado en el nombre."""
#         nombre_normalizado = nombre.strip().lower()
#         cumpleaños_filtrados = [
#             c for c in self.lista_cumpleaños if c['nombre'].strip().lower() != nombre_normalizado
#         ]
#         if len(cumpleaños_filtrados) < len(self.lista_cumpleaños):
#             self.lista_cumpleaños = cumpleaños_filtrados
#             self.guardar_cumpleaños()
#             return True
#         return False
# 
#     def cumpleaños_proximos(self):
#         """Retorna una lista de cumpleaños próximos ordenados."""
#         hoy = datetime.now().date()
#         proximos = []
#         for registro in self.lista_cumpleaños:
#             fecha_nac = datetime.strptime(registro['fecha_nacimiento'], '%Y-%m-%d').date()
#             proximo = fecha_nac.replace(year=hoy.year)
#             if proximo < hoy:
#                 proximo = proximo.replace(year=hoy.year + 1)
#             dias_restantes = (proximo - hoy).days
#             proximos.append({
#                 "nombre": registro['nombre'],
#                 "correo": registro['correo'],
#                 "fecha_nacimiento": registro['fecha_nacimiento'],
#                 "dias_restantes": dias_restantes
#             })
#         return sorted(proximos, key=lambda x: x['dias_restantes'])
# 
# 
# # Clase: EnvioCorreo
# class EnvioCorreo:
#     def __init__(self, email_origen, clave):
#         self.email_origen = email_origen
#         self.clave = clave
#         try:
#             self.cliente_yagmail = yagmail.SMTP(user=self.email_origen, password=self.clave)
#         except Exception as error:
#             raise Exception(f"Error al configurar la conexión de correo: {error}")
# 
#     def enviar_correo(self, email_destino, asunto, contenido):
#         """Envía un correo electrónico."""
#         try:
#             self.cliente_yagmail.send(
#                 to=email_destino,
#                 subject=asunto,
#                 contents=contenido
#             )
#         except Exception as error:
#             raise Exception(f"Error al enviar el correo: {error}")
# 
#     def mensaje_aleatorio(self, archivo_mensajes="mensajes.txt"):
#         """Obtiene un mensaje aleatorio desde un archivo."""
#         try:
#             with open(archivo_mensajes, 'r', encoding='utf-8') as archivo:
#                 mensajes = archivo.readlines()
#             return choice(mensajes).strip()
#         except FileNotFoundError:
#             return "¡Feliz cumpleaños! 🎉"
# 
# 
# # Configuración de la aplicación Streamlit
# gestor = GestorCumpleaños()
# correo = EnvioCorreo(
#     email_origen="diego.moreno0250@alumnos.udg.mx",
#     clave="xrte gcau pbay kkbr"
# )
# 
# st.title("Administrador de Cumpleaños 🎂")
# 
# # Registrar un nuevo cumpleaños
# st.header("Añadir Cumpleaños")
# nombre = st.text_input("Nombre")
# correo_electronico = st.text_input("Correo Electrónico")
# fecha = st.date_input("Fecha de Nacimiento", min_value=datetime(1900, 1, 1), max_value=datetime.now())
# if st.button("Guardar Cumpleaños"):
#     if nombre and correo_electronico and fecha:
#         gestor.agregar_cumpleaños(nombre, correo_electronico, fecha.strftime('%Y-%m-%d'))
#         st.success("Cumpleaños añadido correctamente.")
#     else:
#         st.error("Por favor completa todos los campos.")
# 
# # Mostrar cumpleaños próximos
# st.header("Cumpleaños Próximos")
# cumpleaños = gestor.cumpleaños_proximos()
# if cumpleaños:
#     for persona in cumpleaños:
#         st.write(f"{persona['nombre']} - {persona['dias_restantes']} días ({persona['fecha_nacimiento']})")
# else:
#     st.write("No hay cumpleaños próximos registrados.")
# 
# # Eliminar cumpleaños
# st.header("Eliminar Cumpleaños")
# nombre_eliminar = st.text_input("Nombre del contacto a eliminar")
# if st.button("Eliminar Cumpleaños"):
#     if nombre_eliminar:
#         try:
#             eliminado = gestor.eliminar_cumpleaños(nombre_eliminar.strip())
#             if eliminado:
#                 st.success(f"El cumpleaños de {nombre_eliminar} ha sido eliminado correctamente.")
#                 print(f"Cumpleaños eliminado: {nombre_eliminar}")  # Depuración
#             else:
#                 st.error(f"No se encontró ningún cumpleaños con el nombre: {nombre_eliminar}.")
#                 print(f"No se encontró el cumpleaños de: {nombre_eliminar}")  # Depuración
#         except Exception as e:
#             st.error(f"Error al intentar eliminar el cumpleaños de {nombre_eliminar}: {e}")
#             print(f"Error al eliminar el cumpleaños: {e}")  # Depuración
#     else:
#         st.error("Por favor, ingresa un nombre para eliminar.")
# 
# 
# # Enviar felicitaciones
# st.header("Enviar Felicitaciones Hoy")
# if st.button("Enviar Felicitaciones Hoy"):
#     hoy = datetime.now().date()
#     enviados = False  # Variable para rastrear si se envió al menos un correo
#     for persona in gestor.lista_cumpleaños:
#         try:
#             # Convertir la fecha de nacimiento desde el archivo CSV
#             fecha_nac = datetime.strptime(persona['fecha_nacimiento'], '%Y-%m-%d').date()
#             print(f"Revisando: {persona['nombre']} - Fecha Nacimiento: {fecha_nac}")  # Depuración
#             # Verificar si el cumpleaños es hoy
#             if fecha_nac.month == hoy.month and fecha_nac.day == hoy.day:
#                 print(f"Hoy es el cumpleaños de {persona['nombre']}")  # Depuración
#                 # Obtener mensaje aleatorio y enviar el correo
#                 mensaje = correo.mensaje_aleatorio()
#                 correo.enviar_correo(
#                     email_destino=persona['correo'],
#                     asunto="¡Feliz Cumpleaños! 🎉",
#                     contenido=mensaje
#                 )
#                 st.success(f"Felicitación enviada a {persona['nombre']}")
#                 enviados = True
#         except ValueError:
#             # Manejar errores de formato de fecha
#             st.error(f"Fecha inválida para {persona['nombre']}: {persona['fecha_nacimiento']}")
#             print(f"Error: Fecha inválida para {persona['nombre']}: {persona['fecha_nacimiento']}")  # Depuración
#         except Exception as e:
#             # Manejar errores generales en el envío de correos
#             st.error(f"No se pudo enviar correo a {persona['nombre']}: {e}")
#             print(f"Error al enviar correo a {persona['nombre']}: {e}")  # Depuración
#     # Si no se enviaron felicitaciones
#     if not enviados:
#         st.info("No hay cumpleaños hoy o no se pudieron enviar felicitaciones.")
#

!npm install localtunnel

!streamlit run /content/app.py &>/content/logs.txt &

!npx localtunnel --port 8501